version: '3.8'

services:
  node-exporter:
    image: prom/node-exporter
    container_name: pilot-source
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'

  prometheus:
    image: prom/prometheus:latest
    container_name: pilot-db
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc//prometheus/prometheus.yml
    depends_on:
      - node-exporter
