global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "aegis-api"
    static_configs:
      - targets: ["host.docker.internal:8081"]
